### ISSUE TITLE
How to execute js and lua?

### ISSUE THREAD

**Issue by kreedz** [scrapinghub/scrapy-splash#4]
How to execute js-code that for example pushes the button?
I think can be write a lua-script to execute js-code. But where the lua-script should be placed (in what directory)?
How to integrate this in the scrapy-splash project?

**Comment by kmike** [comment]
No way :) 

We're going to rewrite scrapy-splash soon (today?).

**Comment by kmike** [comment]
Rewrite didn't happen; the alternative implementation is moved here: https://github.com/scrapinghub/scrapyjs

**Comment by kreedz** [comment]
Thanks!
