### ISSUE TITLE
How to wait for more than 10s

### ISSUE THREAD

**Issue by dzlab** [scrapinghub/scrapy-splash#6]
I'm trying to scrap a web site that do some javascript on init to fetch data. The problem is that it takes a long (long) time for it to load but when looking to the [wait argument](http://splash.readthedocs.org/en/latest/api.html#arg-wait) I see it has a 10s max. 
How I could wait for more time?

**Comment by kmike** [comment]
Hi @dzlab,

https://github.com/scrapinghub/scrapyjs is a bit more low-level scrapy+splash integration package; it allows you to use [/execute](http://splash.readthedocs.org/en/latest/api.html#execute) endpoint, and with /execute you can use [splash:wait](http://splash.readthedocs.org/en/latest/scripting-ref.html#splash-wait) which doesn't have 10s limit. 

See also: https://github.com/scrapinghub/splash/issues/146

P.S. I'm not sure scrapy-splash is supported. It is a good idea to switch to scrapyjs.
